services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auction-tcp-server
    restart: unless-stopped
    environment:
      DB_URL: jdbc:mysql://host.docker.internal:3307/auction_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      DB_USER: root
      DB_PASSWORD: 123456
      SERVER_PORT: 5050
      JAVA_OPTS: -Dauction.public.host=localhost -Dauction.media.dir=/app/uploads/images
    ports:
      - "5050:5050"
      - "8081:8081"
    volumes:
      - uploaded_images:/app/uploads

volumes:
  uploaded_images: